### ISSUE TITLE
Adjust game goal

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/Lexinomicon#2]
We need to decide on more specific wording for the goal of our game.
As an initial goal I propose: 

The goal of the game is to develop a healthy bounty economy for the development of Ulex.

**Comment by macterra** [comment]
The [project page](https://cryptotechguru.github.io/Cryptonomicon/Projects/Lexinomicon.html) specifies a goal of "providing governance services and a collaboration space for the Ulex bounty system." We should be consistent.
