### ISSUE TITLE
Improve Ulex footnote links

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Lexinomicon#24]
Make the footnote links bi-directional. Currently the link in the text (e.g. [footnote 1](https://ulex-opensource.github.io/Ulex/versions/1.1/#fn1)) will take you to the footnote but it would be nice if the footnote number was a link to take you back to where it is referenced in the text.

**Comment by macterra** [comment]
Added [Bounty-24](https://github.com/ulex-opensource/Lexinomicon/wiki/Bounty-24) to wiki.

**Comment by macterra** [comment]
[PR#1](https://github.com/ulex-opensource/Ulex/pull/1) submitted

**Comment by macterra** [comment]
@joestartupsocieties merged PR#1. Payment requested https://bounty.cryptotech.guru/payment-requests/a0503990-9e09-4186-9364-2f9a7e0e774a

**Comment by Flaxscrip** [comment]
Treasurer review of Executive's payment request completed. The payment request conforms with the Bounty's terms. Sent instructions to release payment to Executive.

**Comment by macterra** [comment]
Payment received.
